### ISSUE TITLE
Collection of free qwiklabs codes 

### ISSUE THREAD

**Issue by sathishvj** [ddneves/awesome-gcp-certifications#13]
I'll try to keep this updated, hopefully with others also letting me know when there are free codes.

https://medium.com/@sathishvj/qwiklabs-free-codes-gcp-and-aws-e40f3855ffdb

**Comment by ddneves** [comment]
Hey - do wou want to use a repo instead?

I will share ur article right after and add it to the list.

Cheers

**Comment by ddneves** [comment]
Done
