### ISSUE TITLE
Study guides for the Cloud Architect and Data Engineer exams

### ISSUE THREAD

**Issue by ivamluz** [ddneves/awesome-gcp-certifications#24]
I've recently taken and passed both the Cloud Architect and Data Engineer exams.

I've shared my preparation process, as well as **study guides** (TO-DO list style) for both exams in this post: https://medium.com/@ivam.santos/how-to-pass-both-the-cloud-architect-and-data-engineer-gcp-certifications-bb6a0812a1b1

Feel free to add it as a reference in your docs if you feel it's a good fit.

**Comment by ivamluz** [comment]
I also published the study guide for the **Professional Cloud Security Engineer certification** here:  https://medium.com/@ivam.santos/how-to-pass-the-google-professional-cloud-security-engineer-certification-74160bf4d205

**Comment by jmoszuti** [comment]
I recently passed the **Professional Data Engineer** exam as a university graduate and would like to share my experience here as well. Hope this helps! 
https://towardsdatascience.com/how-to-pass-the-google-cloud-professional-data-engineer-exam-f241d7191e47?source=friends_link&sk=ede0b669e5bf68a8e699a3443b9fb087

**Comment by agasthik** [comment]
@ivamluz  @DS-Lite - do you want to add the info and raise a Pull request so that @ddneves  can merge ?
