### ISSUE TITLE
Udemy free course for ACE from cloud; mete's notes on PCA

### ISSUE THREAD

**Issue by sathishvj** [ddneves/awesome-gcp-certifications#6]
Cloud Guru free course for ACE on Udemy: https://www.udemy.com/google-certified-associate-cloud-engineer/?couponCode=GCPFREELY

Mete Atamel's notes on PCA: 
https://medium.com/google-cloud/professional-cloud-architect-certification-6a6dfa5c6ff5

**Comment by ddneves** [comment]
integrated - thanks!
